CREATE TABLE PLANT (
  PLANT_NO NUMBER PRIMARY KEY NOT NULL,
  PLANT_NAME VARCHAR(20) NOT NULL,
  PLANT_COLOR VARCHAR(10),
  ENROLL_DATE DATE
);

CREATE SEQUENCE SEQ_PLANTNO
 START WITH 1
 NOCACHE;

INSERT
  INTO
       PLANT
       (
       PLANT_NO
     , PLANT_NAME
     , PLANT_COLOR
     , ENROLL_DATE
       )
VALUES
       (
       SEQ_PLANTNO.NEXTVAL
     , '토마토'
     , '연두'
     , SYSDATE
       );

SELECT * FROM PLANT;

CREATE TABLE MYTABLE (
  ORDER_NO NUMBER PRIMARY KEY NOT NULL.
  MARKET_NAME VARCHAR(20),
  
);